# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8b23f5156001a5326ecddfe35919a880444025b514646b106637b7b0880a90b45201567137e05b39e44bdddd64bd02040780d31400a07517b72332f7dbfefd11

test:
  secret_key_base: c54484d83a4bc2d169929e73f6b2d9182d59dc483728e4ef39134cf4e6efdeba83b87f953cf67fd9fd3d195308a56ad91eebc3cd0c02c8ed8db14d4cf2c58bc2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
